import { ScriptModules } from "@crowbartools/firebot-custom-scripts-types";

export let childProcess: ScriptModules["childProcess"];
export let commandManager: ScriptModules["commandManager"];
export let conditionManager: ScriptModules["conditionManager"];
export let counterManager: ScriptModules["counterManager"];
export let currencyDb: ScriptModules["currencyDb"];
export let currencyManager: ScriptModules["currencyManager"];
export let customVariableManager: ScriptModules["customVariableManager"];
export let effectManager: ScriptModules["effectManager"];
export let effectRunner: ScriptModules["effectRunner"];
export let eventFilterFactory: ScriptModules["eventFilterFactory"];
export let eventFilterManager: ScriptModules["eventFilterManager"];
export let eventManager: ScriptModules["eventManager"];
export let firebotRolesManager: ScriptModules["firebotRolesManager"];
export let frontendCommunicator: ScriptModules["frontendCommunicator"];
export let fs: ScriptModules["fs"];
export let gameManager: ScriptModules["gameManager"];
export let howler: ScriptModules["howler"];
export let httpServer: ScriptModules["httpServer"];
export let integrationManager: ScriptModules["integrationManager"];
export let JsonDb: ScriptModules["JsonDb"];
export let logger: ScriptModules["logger"];
export let moment: ScriptModules["moment"];
export let notificationManager: ScriptModules["notificationManager"];
export let overlayWidgetConfigManager: ScriptModules["overlayWidgetConfigManager"];
export let overlayWidgetsManager: ScriptModules["overlayWidgetsManager"];
export let path: ScriptModules["path"];
export let quotesManager: ScriptModules["quotesManager"];
export let replaceVariableFactory: ScriptModules["replaceVariableFactory"];
export let replaceVariableManager: ScriptModules["replaceVariableManager"];
export let twitchApi: ScriptModules["twitchApi"];
export let uiExtensionManager: ScriptModules["uiExtensionManager"];
export let utils: ScriptModules["utils"];

export function initModules(scriptModules: ScriptModules) {
  childProcess = scriptModules.childProcess;
  commandManager = scriptModules.commandManager;
  conditionManager = scriptModules.conditionManager;
  counterManager = scriptModules.counterManager;
  currencyDb = scriptModules.currencyDb;
  currencyManager = scriptModules.currencyManager;
  customVariableManager = scriptModules.customVariableManager;
  effectManager = scriptModules.effectManager;
  effectRunner = scriptModules.effectRunner;
  eventFilterFactory = scriptModules.eventFilterFactory;
  eventFilterManager = scriptModules.eventFilterManager;
  eventManager = scriptModules.eventManager;
  firebotRolesManager = scriptModules.firebotRolesManager;
  frontendCommunicator = scriptModules.frontendCommunicator;
  fs = scriptModules.fs;
  gameManager = scriptModules.gameManager;
  howler = scriptModules.howler;
  httpServer = scriptModules.httpServer;
  integrationManager = scriptModules.integrationManager;
  JsonDb = scriptModules.JsonDb;
  logger = scriptModules.logger;
  moment = scriptModules.moment;
  notificationManager = scriptModules.notificationManager;
  overlayWidgetConfigManager = scriptModules.overlayWidgetConfigManager;
  overlayWidgetsManager = scriptModules.overlayWidgetsManager;
  path = scriptModules.path;
  quotesManager = scriptModules.quotesManager;
  replaceVariableFactory = scriptModules.replaceVariableFactory;
  replaceVariableManager = scriptModules.replaceVariableManager;
  twitchApi = scriptModules.twitchApi;
  utils = scriptModules.utils;
  uiExtensionManager = scriptModules.uiExtensionManager;
}
